In [4]:
import pandas as pd
import project_config

In [13]:
df = pd.read_csv(f"{project_config.RAW}/Attraction_Belem.csv",encoding="utf-8").drop(axis=1,columns=['Unnamed: 0'])
df.head()

,Name,Rating_attaction,Username,Title_Review,Rating_Review,Review,Date,State,Type_traveler
0,Estação das Docas,45,Volnei Castanho,Local agradável!,50,"Local reformado, bem ao estilo de Puerto Mader...",fevereiro de 2020,"Barueri, SP",Families
1,Estação das Docas,45,Alexandre Mendes,Lugar incrível,50,Lugar incrível para visualizar o melhor por So...,janeiro de 2020,"Belém, PA",Families
2,Estação das Docas,45,Airton C,Muitas opções em um só lugar,50,O espaço é muito bonito e agradável com várias...,março de 2020,"Ouro Preto, MG",Families
3,Estação das Docas,45,marcos l,Restaurante,50,Um ótimo lugar para levar a família é deslumb...,fevereiro de 2020,"Belém, PA",Families
4,Estação das Docas,45,Ana Caroline T,Top,50,Vale demais a visita! Lugar agradável em Belém...,fevereiro de 2020,"Foz do Iguaçu, PR",Families

In [14]:
df.columns

Index(['Name', 'Rating_attaction', 'Username', 'Title_Review', 'Rating_Review',
       'Review', 'Date', 'State', 'Type_traveler'],
      dtype='object')

In [15]:
df.describe(include="all")

,Name,Rating_attaction,Username,Title_Review,Rating_Review,Review,Date,State,Type_traveler
count,14098,14098.000000,14098,14098,14098.000000,14098,14098,11884,14098
unique,10,NaN,6556,9336,NaN,14098,108,829,5
top,Estação das Docas,NaN,Eliane M,Lindo,NaN,Antigamente era um hangar para guardar pequeno...,março de 2016,"Belém, PA",Families
freq,4877,NaN,18,205,NaN,1,441,2392,4271
mean,NaN,45.381969,NaN,NaN,45.699390,NaN,NaN,NaN,NaN
std,NaN,2.147602,NaN,NaN,6.610142,NaN,NaN,NaN,NaN
min,NaN,40.000000,NaN,NaN,10.000000,NaN,NaN,NaN,NaN
25%,NaN,45.000000,NaN,NaN,40.000000,NaN,NaN,NaN,NaN
50%,NaN,45.000000,NaN,NaN,50.000000,NaN,NaN,NaN,NaN
75%,NaN,45.000000,NaN,NaN,50.000000,NaN,NaN,NaN,NaN
max,NaN,50.000000,NaN,NaN,50.000000,NaN,NaN,NaN,NaN

In [16]:
df.dtypes

Name                object
Rating_attaction     int64
Username            object
Title_Review        object
Rating_Review        int64
Review              object
Date                object
State               object
Type_traveler       object
dtype: object

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14098 entries, 0 to 14097
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Name              14098 non-null  object
 1   Rating_attaction  14098 non-null  int64
 2   Username          14098 non-null  object
 3   Title_Review      14098 non-null  object
 4   Rating_Review     14098 non-null  int64
 5   Review            14098 non-null  object
 6   Date              14098 non-null  object
 7   State             11884 non-null  object
 8   Type_traveler     14098 non-null  object
dtypes: int64(2), object(7)
memory usage: 991.4+ KB

In [19]:
df_bronze = df[df["Name"].notna() & (df["Name"].astype("string").str.strip() != "")].copy()
df_bronze.head(5)

,Name,Rating_attaction,Username,Title_Review,Rating_Review,Review,Date,State,Type_traveler
0,Estação das Docas,45,Volnei Castanho,Local agradável!,50,"Local reformado, bem ao estilo de Puerto Mader...",fevereiro de 2020,"Barueri, SP",Families
1,Estação das Docas,45,Alexandre Mendes,Lugar incrível,50,Lugar incrível para visualizar o melhor por So...,janeiro de 2020,"Belém, PA",Families
2,Estação das Docas,45,Airton C,Muitas opções em um só lugar,50,O espaço é muito bonito e agradável com várias...,março de 2020,"Ouro Preto, MG",Families
3,Estação das Docas,45,marcos l,Restaurante,50,Um ótimo lugar para levar a família é deslumb...,fevereiro de 2020,"Belém, PA",Families
4,Estação das Docas,45,Ana Caroline T,Top,50,Vale demais a visita! Lugar agradável em Belém...,fevereiro de 2020,"Foz do Iguaçu, PR",Families

In [20]:
date_text = df_bronze["Date"].astype("string").str.lower()

month_patterns = {
    r"janeiro": "01",
    r"fevereiro": "02",
    r"março|marco|marÃ§o": "03",
    r"abril": "04",
    r"maio": "05",
    r"junho": "06",
    r"julho": "07",
    r"agosto": "08",
    r"setembro": "09",
    r"outubro": "10",
    r"novembro": "11",
    r"dezembro": "12"
}

month = pd.Series(pd.NA, index=df_bronze.index, dtype="string")
for pattern, value in month_patterns.items():
    month = month.mask(date_text.str.contains(pattern, regex=True, na=False), value)

year = date_text.str.extract(r"(\d{4})", expand=False)
df_bronze["Date_Travel"] = pd.to_datetime(
    year + "-" + month + "-01",
    format="%Y-%m-%d",
    errors="coerce"
)

df_bronze["Rating_Review"] = pd.to_numeric(df_bronze["Rating_Review"], errors="coerce").astype("Int64")
df_bronze["Rating_attaction"] = pd.to_numeric(df_bronze["Rating_attaction"], errors="coerce").astype("Int64")
df_bronze.head(5)

,Name,Rating_attaction,Username,Title_Review,Rating_Review,Review,Date,State,Type_traveler,Date_Travel
0,Estação das Docas,45,Volnei Castanho,Local agradável!,50,"Local reformado, bem ao estilo de Puerto Mader...",fevereiro de 2020,"Barueri, SP",Families,2020-02-01
1,Estação das Docas,45,Alexandre Mendes,Lugar incrível,50,Lugar incrível para visualizar o melhor por So...,janeiro de 2020,"Belém, PA",Families,2020-01-01
2,Estação das Docas,45,Airton C,Muitas opções em um só lugar,50,O espaço é muito bonito e agradável com várias...,março de 2020,"Ouro Preto, MG",Families,2020-03-01
3,Estação das Docas,45,marcos l,Restaurante,50,Um ótimo lugar para levar a família é deslumb...,fevereiro de 2020,"Belém, PA",Families,2020-02-01
4,Estação das Docas,45,Ana Caroline T,Top,50,Vale demais a visita! Lugar agradável em Belém...,fevereiro de 2020,"Foz do Iguaçu, PR",Families,2020-02-01

In [21]:
df_bronze.head(5)

,Name,Rating_attaction,Username,Title_Review,Rating_Review,Review,Date,State,Type_traveler,Date_Travel
0,Estação das Docas,45,Volnei Castanho,Local agradável!,50,"Local reformado, bem ao estilo de Puerto Mader...",fevereiro de 2020,"Barueri, SP",Families,2020-02-01
1,Estação das Docas,45,Alexandre Mendes,Lugar incrível,50,Lugar incrível para visualizar o melhor por So...,janeiro de 2020,"Belém, PA",Families,2020-01-01
2,Estação das Docas,45,Airton C,Muitas opções em um só lugar,50,O espaço é muito bonito e agradável com várias...,março de 2020,"Ouro Preto, MG",Families,2020-03-01
3,Estação das Docas,45,marcos l,Restaurante,50,Um ótimo lugar para levar a família é deslumb...,fevereiro de 2020,"Belém, PA",Families,2020-02-01
4,Estação das Docas,45,Ana Caroline T,Top,50,Vale demais a visita! Lugar agradável em Belém...,fevereiro de 2020,"Foz do Iguaçu, PR",Families,2020-02-01

In [37]:
#--------------Modelagem-------------
# Attraction -> ID, Name, Rating_attraction
### User -> ID, Username, State (Cardinality problem)
# User_Review -> ID, ID_User, ID_Attraction, Title_Review, Rating_Review, Review, Username, State, Type_traveler, Date

In [22]:
df_dim_silver_attractions = (
    df_bronze.loc[
        df_bronze["Name"].notna() & (df_bronze["Name"].astype("string").str.strip() != ""),
        ["Name", "Rating_attaction"]
    ]
    .drop_duplicates(subset=["Name"])
    .sort_values("Name")
    .reset_index(drop=True)
)

df_dim_silver_attractions["Attraction_id"] = (df_dim_silver_attractions.index + 1).astype("Int64")
df_dim_silver_attractions["Rating_Attraction"] = pd.to_numeric(
    df_dim_silver_attractions["Rating_attaction"],
    errors="coerce"
).astype("Int64")

df_dim_silver_attractions = df_dim_silver_attractions[["Attraction_id", "Name", "Rating_Attraction"]]
df_dim_silver_attractions.head(100)

   Attraction_id                                     Name  Rating_Attraction
0              1      Basílica de Nossa Senhora de Nazaré                 50
1              2                        Estação das Docas                 45
2              3                        Forte do Presépio                 45
3              4  Hangar Centro de Convenções da Amazônia                 45
4              5                        Mangal das Garças                 45
5              6             Museu Paraense Emílio Goeldi                 45
6              7                Parque Estadual do Utinga                 45
7              8                     Parque da Residência                 45
8              9                       Praça da República                 40
9             10                            Teatro da Paz                 45

In [23]:
df_fact_silver_reviews = df_bronze.drop(columns=["Rating_attaction", "Date"]).copy()

fact = df_fact_silver_reviews.copy()
dim = df_dim_silver_attractions.copy()

fact["_name_key"] = fact["Name"].astype("string").str.lower()
dim["_name_key"] = dim["Name"].astype("string").str.lower()

df_fact_silver_reviews = (
    fact.merge(
        dim[["_name_key", "Attraction_id", "Rating_Attraction"]],
        on="_name_key",
        how="left"
    )
    .drop(columns=["Name", "Rating_Attraction", "_name_key"])
)

df_fact_silver_reviews.head(5)

,Username,Title_Review,Rating_Review,Review,State,Type_traveler,Date_Travel,Attraction_id
0,Volnei Castanho,Local agradável!,50,"Local reformado, bem ao estilo de Puerto Mader...","Barueri, SP",Families,2020-02-01,2
1,Alexandre Mendes,Lugar incrível,50,Lugar incrível para visualizar o melhor por So...,"Belém, PA",Families,2020-01-01,2
2,Airton C,Muitas opções em um só lugar,50,O espaço é muito bonito e agradável com várias...,"Ouro Preto, MG",Families,2020-03-01,2
3,marcos l,Restaurante,50,Um ótimo lugar para levar a família é deslumb...,"Belém, PA",Families,2020-02-01,2
4,Ana Caroline T,Top,50,Vale demais a visita! Lugar agradável em Belém...,"Foz do Iguaçu, PR",Families,2020-02-01,2

# Quality Tests dim attractions

In [24]:
def append_validation_error(df, condition, error_code):
    cond = condition.fillna(False)
    df.loc[cond, "validation_errors"] = df.loc[cond, "validation_errors"] + error_code


df_validation_dim_attractions = df_dim_silver_attractions.copy()
df_validation_dim_attractions["validation_errors"] = ""

append_validation_error(
    df_validation_dim_attractions,
    df_validation_dim_attractions["Attraction_id"].isna(),
    "ID_NULL;"
)

duplicate_ids = df_validation_dim_attractions["Attraction_id"].duplicated(keep=False)
append_validation_error(
    df_validation_dim_attractions,
    duplicate_ids,
    "ID_NOT_UNIQUE;"
)

invalid_rating_attr = (
    (df_validation_dim_attractions["Rating_Attraction"] <= 0)
    | (df_validation_dim_attractions["Rating_Attraction"] > 50)
)
append_validation_error(
    df_validation_dim_attractions,
    invalid_rating_attr,
    "RATING_ATTRACTION_INVALID;"
)

append_validation_error(
    df_validation_dim_attractions,
    df_validation_dim_attractions["Name"].isna(),
    "NAME_NULL;"
)

df_validation_dim_attractions["is_valid"] = (
    df_validation_dim_attractions["validation_errors"].str.strip() == ""
)

df_dim_invalid_attractions = (
    df_validation_dim_attractions.loc[~df_validation_dim_attractions["is_valid"]]
    .drop(columns=["is_valid"])
)
df_dim_gold_attractions = (
    df_validation_dim_attractions.loc[df_validation_dim_attractions["is_valid"]]
    .drop(columns=["is_valid", "validation_errors"])
)

# Quality Tests fact reviews

In [25]:
df_validation_fact_reviews = df_fact_silver_reviews.copy()
df_validation_fact_reviews["validation_errors"] = ""

append_validation_error(
    df_validation_fact_reviews,
    df_validation_fact_reviews["Username"].isna(),
    "USERNAME_NULL;"
)

invalid_rating_review = (
    (df_validation_fact_reviews["Rating_Review"] <= 0)
    | (df_validation_fact_reviews["Rating_Review"] > 50)
)
append_validation_error(
    df_validation_fact_reviews,
    invalid_rating_review,
    "RATING_REVIEW_INVALID;"
)

append_validation_error(
    df_validation_fact_reviews,
    df_validation_fact_reviews["Review"].isna(),
    "REVIEW_NULL;"
)

append_validation_error(
    df_validation_fact_reviews,
    df_validation_fact_reviews["Date_Travel"].isna(),
    "DATE_NULL;"
)

categories = ["couples", "families", "alone", "business", "friends"]
traveler_clean = df_validation_fact_reviews["Type_traveler"].astype("string").str.strip().str.lower()
invalid_type = df_validation_fact_reviews["Type_traveler"].isna() | (~traveler_clean.isin(categories).fillna(False))
append_validation_error(
    df_validation_fact_reviews,
    invalid_type,
    "TYPE_TRAVELER_INVALID;"
)

df_validation_fact_reviews["is_valid"] = (
    df_validation_fact_reviews["validation_errors"].str.strip() == ""
)

df_fact_invalid_reviews = (
    df_validation_fact_reviews.loc[~df_validation_fact_reviews["is_valid"]]
    .drop(columns=["is_valid"])
)
df_fact_gold_reviews = (
    df_validation_fact_reviews.loc[df_validation_fact_reviews["is_valid"]]
    .drop(columns=["is_valid", "validation_errors"])
)
# df_fact_invalid_reviews.head()

In [ ]:
# ---- Exportation ------

# Bronze
df_bronze.to_csv(f"{project_config.BRONZE}/df_bronze.csv")

# Silver
df_fact_silver_reviews.to_csv(f"{project_config.SILVER}/fact_reviews.csv")
df_dim_silver_attractions.to_csv(f"{project_config.SILVER}/dim_attractions.csv")

# Gold
df_fact_gold_reviews.to_csv(f"{project_config.GOLD}/fact_reviews.csv", index=False)
df_dim_gold_attractions.to_csv(f"{project_config.GOLD}/dim_attractions.csv", index=False)

# Invalid Bucket
df_fact_invalid_reviews.to_csv(f"{project_config.INVALID}/fact_reviews_invalid.csv")
df_dim_invalid_attractions.to_csv(f"{project_config.INVALID}/dim_invalid.csv")